<h3>Enter new game condition</h3>
<form action="<?php echo $this->getUrl('games/index/addnewgamesuccess')?>" method="post">
    <div>Title</div>
    <input type="text" name="title" value="title">
    <div>Description</div>
    <input type="text" name="description" value="description">
    <div>Creator</div>
    <input type="text" name="creator" value="creator">
    <div>Way to picture</div>
    <input type="text" name="picture" value="picture">
    </br>
    <button type="submit" class="button" title="<?php echo $this->__('Add') ?>">
        <span><span><?php echo $this->__('Add') ?></span></span></button>
</form>