<h3>Delete game</h3>
<!--<form action="<?php echo $this->getUrl('games/index/deletegamesuccess')?>" method="post">
    <div>Id</div>
    <input type="text" name="id">
    </br>
    <button type="submit" class="button" title="<?php echo $this->__('Delete') ?>">
        <span><span><?php echo $this->__('Delete') ?></span></span></button>
</form>-->
<form action="<?php echo $this->getUrl('games/index/deletegamesuccess')?>" method="post">
    <select name="id">
        <?php foreach ($this->getEavCollection() as $gameModel):?>
            <option value="<?php echo $gameModel->getId()?>"><?php echo $gameModel->getTitle()?></option>
        <?php endforeach;?>
    </select>
    <button type="submit" class="button" title="<?php echo $this->__('Delete') ?>">
        <span><span><?php echo $this->__('Delete') ?></span></span></button>

</form>