<!--
 * @category    Training
 * @package     Training_Helloworld
 * @copyright   Copyright (c) 2006-2019 Magento, Inc. (http://www.magento.com)
 * @license     Smile
-->

<?php echo $this->myfunction(); ?> <br>
<?php echo $this->getChildHtml('mymodule2')?>

<p>below is collection</p>
<?php foreach ($this->showCollection() as $item): ?>
  <h2>  <a href="/first/index/detail/id/<?php echo $item->getBlogpostId();?>"><?php echo $item->getTitle() ?></a> </h2>
    <p><?php echo $item->getDate() ?></p>
<?php endforeach; ?>

<br>

<p>below is loaded model by parameter</p>
<!--<h3>-->
<!--    --><?php
//    $params = $this->getRequest()->getParams();
//    echo $this->loadModel($params['id'])->getTitle(); ?>
<!--</h3>-->

